### ISSUE TITLE
Курсовая работа

### ISSUE THREAD

**Issue by FlashAnton** [LIMVX/METODIPROG#8]
Здравствуйте.

Обратите, пожалуйста, внимание, что в Учебных материалах появился раздел "Курсовая работа".

"Рабочее задание. Типовая схема" - то, что необходимо реализовать.
"Структура" - разделы отчётного документа Word по курсовой работе.

В каталоге, содержащем сводные сведения о почасовой нагрузке преподавателей в текстовом файле прописаны пункты,
которые необходимо отразить на Chart-элементе.

Данная ветвь предназначена для обсуждения всех вопросов по Курсовой работе.

**Comment by LIMVX** [comment]
Здравствуйте, Антон Игоревич. Мы поправили отчет к курсовой работе в соответствии с вашими замечаниями

[Uploading 24062024_БузаджиНМ_СамохваловаМД_Вар9_Курсовая_работа.docx…]()

**Comment by FlashAnton** [comment]
Здравствуйте.

Отчёт посмотрел. Связку по сети Петри Вы придумали очень удачную. Я такой всецело согласен.

Теперь о Вас требуется загрузить финальную версию docx (можно преобразовать в pdf) на сайт РУТ (МИИТ) в портфолио.

И ещё проверить комплектность размещённых в репозитории материалов. Я одной из работ у Вас не досчитываюсь. После демонстрации с ноутбука в вузе Вы, вероятно, забыли прикрепить отчёт и ПО.

**Comment by FlashAnton** [comment]
Теперь всё в порядке.

**За Курсовую работу - "отлично".**

Остальные *Issues* по лабораторным работам с резолюциями о выполнении закрою позже.

Не то, чтобы это обязательное мероприятие, но для порядка мне следует это сделать.
Просто не пугайтесь сообщениям, которые завтра-послезавтра поступят на электронную почту.
Решение в отношении Вашей бригады по дисциплине принято и отмене не подлежит.
